image: registry.gitlab.com/corneliusludmann/gitlab-development-kit/gitpod-workspace:gitpod-workspace-image

tasks:

  - name: GDK
    command: gp sync-await gdk-copied && cd /workspace/gitlab-development-kit && gdk help

  - init: |
      echo "$(date) – Copying GDK" | tee -a /workspace/startup.log
      mv $HOME/.rvm-workspace /workspace/.rvm
      cp -r $HOME/gitlab-development-kit /workspace/
      (
        set -e
        cd /workspace/gitlab-development-kit
        [[ ! -L /workspace/gitlab-development-kit/gitlab ]] && ln -fs /workspace/gitlab /workspace/gitlab-development-kit/gitlab
        # make webpack static, prevents that GitLab tries to connect to localhost webpack from browser outside the workspace
        echo "webpack:" >> gdk.yml
        echo "  static: true" >> gdk.yml
        # reconfigure GDK
        echo "$(date) – Reconfiguring GDK" | tee -a /workspace/startup.log
        gdk reconfigure
        # run DB migrations
        echo "$(date) – Running DB migrations" | tee -a /workspace/startup.log
        printf "Waiting for GitLab database ..."
        until gdk psql -d gitlabhq_development -c '\l' >/dev/null 2>/dev/null; do printf '.'; sleep 5; done && echo ""
        cd gitlab
        rails db:migrate RAILS_ENV=development
        REQUIRES_RESTART=true
        cd -
        # stopping GitLab
        echo "$(date) – Stopping GDK" | tee -a /workspace/startup.log
        gdk stop
        echo "$(date) – GDK stopped" | tee -a /workspace/startup.log
      )
    command: |
      (
        set -e
        gp sync-done gdk-copied
        SECONDS=0
        cd /workspace/gitlab-development-kit
        # add Gitpod URL to allowed hosts
        echo "if Rails.env.development?" > gitlab/config/initializers/rails_host_authorization_gitpod.rb
        echo "  Rails.application.config.hosts += [\"$(gp url 3000 | sed -e 's+^http://++' -e 's+^https://++')\"]" >> gitlab/config/initializers/rails_host_authorization_gitpod.rb
        echo "end" >> gitlab/config/initializers/rails_host_authorization_gitpod.rb
        echo "rails_host_authorization_gitpod.rb" > gitlab/.git/info/exclude
        # update GDK
        if [ "$GITLAB_UPDATE_GDK" = true ]; then
          echo "$(date) – Updating GDK" | tee -a /workspace/startup.log
          gdk update
        fi
        # start GitLab
        echo "$(date) – Starting GDK" | tee -a /workspace/startup.log
        gdk start
        # Run DB migrations
        if [ "$GITLAB_RUN_DB_MIGRATIONS" = true ]; then
          echo "$(date) – Running DB migrations" | tee -a /workspace/startup.log
          printf "Waiting for GitLab database ..."
          until gdk psql -d gitlabhq_development -c '\l' >/dev/null 2>/dev/null; do printf '.'; sleep 5; done && echo ""
          cd gitlab
          # Run DB migrations
          rails db:migrate RAILS_ENV=development
          cd -
        fi
        # Fix DB key
        if [ "$GITLAB_FIX_DB_KEY" = true ]; then
          echo "$(date) – Fixing DB key" | tee -a /workspace/startup.log
          cd gitlab
          # see https://gitlab.com/gitlab-org/gitlab-foss/-/issues/56403#note_132515069
          printf 'ApplicationSetting.last.update_column(:runners_registration_token_encrypted, nil)\nexit\n' | bundle exec rails c
          cd -
        fi
        # Waiting for GitLab ...
        gp await-port 3000
        printf "Waiting for GitLab at $(gp url 3000) ..."
        until $(curl -sNL $(gp url 3000) | grep -q "GitLab"); do printf '.'; sleep 5; done && echo ""
        # Give Gitpod a few more seconds to set up everything ...
        sleep 5
        printf "$(date) – GitLab is up (took ~%.1f minutes)\n" "$((10*$SECONDS/60))e-1" | tee -a /workspace/startup.log
        gp preview $(gp url 3000) || true
      )

ports:
  - port: 3000
    onOpen: ignore
  - port: 3010
    onOpen: ignore
  - port: 3808
    onOpen: ignore
  - port: 5778
    onOpen: ignore

vscode:
  extensions:
    - rebornix.ruby@0.27.0:QyGBeRyslOfdRgOPRGm6PQ==
    - wingrunr21.vscode-ruby@0.27.0:beIqQUhLRuJ5Vao4B2Lyng==
    - karunamurti.haml@1.1.0:twCwOYt3/Ttfb3+iwblPDA==
    - octref.vetur@0.25.0:UofirBhedyhdx/jCnPeJDg==
    - dbaeumer.vscode-eslint@2.1.3:1NRvj3UKNTNwmYjptmUmIw==
