#!/bin/bash

# Look for jq presence. Needed for JSON parsing
if [ -x "$(command -v jq)" ]
then
  jq_version=$(jq --version)
  echo "jq detected: $jq_version"
else
  echo 'No jq version detected. Please install the `jq` package for your operating system.'
  exit 0
fi

# Check the project ID
if [ -n "$1" ] && [ "$1" -eq "$1" ] 2>/dev/null;
then
  echo "Custom project ID found"

  project_id=$1
  source_branch=$2
  target_branch=$3
else
  echo "Default project ID being used"

  project_id="278964"
  source_branch=$1
  target_branch=$2
fi

echo "Project ID: $project_id"

# Check branch names
if [ -z "$source_branch" ]
then
  echo "Source branch name is required"
  exit 0
fi

if [ -z "$target_branch" ]
then
  echo "Target branch name is required"
  exit 0
fi

echo "Will rebase $source_branch onto $target_branch"
echo "Fetching latest $source_branch"
git checkout $source_branch
git pull origin $source_branch

echo "Fetching last successful pipeline run for $source_branch"

sha=$(curl --request GET --url "https://gitlab.com/api/v4/projects/$project_id/pipelines?status=success&ref=$source_branch" | jq -r ".[0] | .sha")

if [ -z "$sha" ]
then
  echo "Failed to get a valid SHA for a good rebase"
  exit 0
fi

echo "Rebasing up to $sha"

git checkout $target_branch
git rebase $sha $target_branch
