---
name: improved_mr_merged_at_queries
introduced_by_url: https://gitlab.com/gitlab-org/gitlab/-/merge_requests/39329
rollout_issue_url: 
group: group::analytics
type: development
default_enabled: true
