---
name: snippets_edit_vue
introduced_by_url: https://gitlab.com/gitlab-org/gitlab/-/merge_requests/25667
rollout_issue_url: https://gitlab.com/gitlab-org/gitlab/-/issues/207239
group: group::editor
type: development
default_enabled: true
