---
name: sast_configuration_ui
introduced_by_url: https://gitlab.com/gitlab-org/gitlab/-/merge_requests/34947
rollout_issue_url: https://gitlab.com/gitlab-org/gitlab/-/issues/235135
group: group::static analysis
type: development
default_enabled: true
