#!/usr/bin/env ruby

# This script is used both in CI and in local development 'rspec' runs.

require_relative 'gitaly_test'

class GitalyTestSpawn
  include GitalyTest

  def run
    check_gitaly_config!

    # In local development this pid file is used by rspec.
    IO.write(File.expand_path('../tmp/tests/gitaly.pid', __dir__), start('gitaly'))
    IO.write(File.expand_path('../tmp/tests/praefect.pid', __dir__), start('praefect'))
  end
end

GitalyTestSpawn.new.run
