#!/usr/bin/env ruby

require 'digest'
require 'fileutils'

harness_path = File.expand_path('../.git/security_harness', __dir__)

# Toggle the harness on or off
if File.exist?(harness_path)
  FileUtils.rm(harness_path)

  puts "Security harness removed -- you can now push to all remotes."
else
  FileUtils.touch(harness_path)

  puts "Security harness installed -- you will only be able to push to dev.gitlab.org!"
  puts "Make sure you have OVERCOMMIT installed for the harness to work!"
end
