source 'https://rubygems.org'

gem 'gitlab-qa'
gem 'activesupport', '5.2.3' # This should stay in sync with the root's Gemfile
gem 'pry-byebug', '~> 3.5.1', platform: :mri
gem 'capybara', '~> 3.22.0'
gem 'capybara-screenshot', '~> 1.0.22'
gem 'rake', '~> 12.3.0'
gem 'rspec', '~> 3.8.0'
gem 'selenium-webdriver', '~> 3.141'
gem 'airborne', '~> 0.2.13'
gem 'nokogiri', '~> 1.10.4'
gem 'rspec-retry', '~> 0.6.1'
gem 'rspec_junit_formatter'
gem 'ffaker', '~> 2.10'
gem 'knapsack', '~> 1.17'
gem 'parallel_tests', '~> 2.29'
